<metal:html tal:define="showthirdcol nothing;
                        debugging python:1;
                        treated python:('NotFound','KeyError','NameError');
                        error_type options/error_type|nothing;
                        error_value options/error_value|nothing;
                        error_message options/error_message|nothing;
                        error_tb options/error_tb|nothing;
                        error_traceback options/error_traceback|nothing;
                        error_log_url options/error_log_url|nothing;
                       ">
<metal:body use-macro="here/main_template/macros/master">

<metal:main fill-slot="main">

<tal:haserror condition="error_type">
  <tal:NotFound condition="python:error_type == 'NotFound'">
    <metal:block use-macro="here/error_lib/macros/not_found" />
  </tal:NotFound>

  <tal:KeyNameError condition="python:error_type in ('KeyError','NameError')">
    <metal:block use-macro="here/error_lib/macros/key_or_name" />
  </tal:KeyNameError>

  <tal:other condition="python:error_type not in treated">
    <metal:block use-macro="here/error_lib/macros/other" />
  </tal:other>

  <tal:debugging condition="debugging">
    <strong>Error Type: <span tal:replace="error_type" /></strong>
    <br>
    <strong>Error Value:</strong>
    <pre tal:content="structure error_value" />
    
    <hr>
    <strong>Traceback:</strong>
    <pre tal:content="structure error_traceback" />
    <strong>Request:</strong>
    <pre tal:content="structure request" />
    
    <hr>
    <a href="" tal:condition="python:error_log_url and debugging"
               tal:attributes="href error_log_url">
      Show Error Log Entry
    </a>
  </tal:debugging>
</tal:haserror>

<tal:hasnoerror tal:condition="not:error_type">
  In Heaven, everything's fine...
</tal:hasnoerror>

</metal:main>
</metal:body>
</metal:html>
